apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sudokudev42@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: addon-http-application-routing
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-dns-dev
spec:
  secretName: letsencrypt
  dnsNames:
  - sudoku-dev.073ed16829504d398ee5.eastus.aksapp.io
  issuerRef:   
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-dns-prod
spec:
  secretName: letsencrypt
  dnsNames:
  - 073ed16829504d398ee5.eastus.aksapp.io
  issuerRef:   
    name: letsencrypt
    kind: ClusterIssuer
