apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: sudoku-dev
  name: sudoku-dev
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"kubernetes.io/metadata.name":"sudoku-dev"},"name":"sudoku-dev"}}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sudoku-dev-limit-range
  namespace: sudoku-dev
spec:
  limits:
  - default:
      cpu: 200m
      memory: 400Mi
    defaultRequest:
      cpu: 100m
      memory: 200Mi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sudoku-dev-resource-quota
  namespace: sudoku-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "3"
    limits.memory: 4Gi
    persistentvolumeclaims: "1"
    requests.storage: "2Gi"
