apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: sudoku-prod
  name: sudoku-prod
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"kubernetes.io/metadata.name":"sudoku-prod"},"name":"sudoku-prod"}}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sudoku-prod-limit-range
  namespace: sudoku-prod
spec:
  limits:
  - default:
      cpu: 300m
      memory: 600Mi
    defaultRequest:
      cpu: 200m
      memory: 300Mi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sudoku-prod-resource-quota
  namespace: sudoku-prod
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 6Gi
    persistentvolumeclaims: "1"
    requests.storage: "20Gi"
