from enum import IntEnum


class Weekday(IntEnum):
    MONDAY_WEEKDAY = 0
    TUESDAY_WEEKDAY = 1
    WEDNESDAY_WEEKDAY = 2
    THURSDAY_WEEKDAY = 3
    FRIDAY_WEEKDAY = 4
    SATURDAY_WEEKDAY = 5
    SUNDAY_WEEKDAY = 6


USER_NOT_FOUND = "User not found"

SCALAR = 100
NUM_DAYS = 30
PAZAM_THRESHOLD = 60

MONDAY_WEEKDAY = 0
TUESDAY_WEEKDAY = 1
WEDNESDAY_WEEKDAY = 2
THURSDAY_WEEKDAY = 3
FRIDAY_WEEKDAY = 4
SATURDAY_WEEKDAY = 5
SUNDAY_WEEKDAY = 6
